/*-----------------------------------------------------------------------------
  03_bootstrap_load.sql
  -----------------------------------------------------------------------------
  Loads the 6 sample CSVs from the internal stage STG_FIN_BOOTSTRAP into the
  FIN_RAW tables. Use this for POC / demo. In production Fivetran replaces
  this entirely.

  Pre-req: upload the files locally first:
      PUT file://data/raw/customers.csv     @STG_FIN_BOOTSTRAP AUTO_COMPRESS=TRUE;
      PUT file://data/raw/accounts.csv      @STG_FIN_BOOTSTRAP AUTO_COMPRESS=TRUE;
      PUT file://data/raw/transactions.csv  @STG_FIN_BOOTSTRAP AUTO_COMPRESS=TRUE;
      PUT file://data/raw/loans.csv         @STG_FIN_BOOTSTRAP AUTO_COMPRESS=TRUE;
      PUT file://data/raw/branches.csv      @STG_FIN_BOOTSTRAP AUTO_COMPRESS=TRUE;
      PUT file://data/raw/calendar_dim.csv  @STG_FIN_BOOTSTRAP AUTO_COMPRESS=TRUE;
-----------------------------------------------------------------------------*/

USE ROLE FIN_ADMIN;
USE WAREHOUSE WH_FIN_INGEST;
USE SCHEMA FIN_ANALYTICS.FIN_RAW;

-- truncate for idempotent reload
TRUNCATE TABLE IF EXISTS RAW_CUSTOMERS;
TRUNCATE TABLE IF EXISTS RAW_ACCOUNTS;
TRUNCATE TABLE IF EXISTS RAW_TRANSACTIONS;
TRUNCATE TABLE IF EXISTS RAW_LOANS;
TRUNCATE TABLE IF EXISTS RAW_BRANCHES;
TRUNCATE TABLE IF EXISTS RAW_CALENDAR_DIM;

COPY INTO RAW_CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_SEGMENT,RISK_CATEGORY,REGION,ONBOARDING_DATE)
    FROM @STG_FIN_BOOTSTRAP/customers.csv.gz
    FILE_FORMAT = (FORMAT_NAME = FF_CSV_STD)
    ON_ERROR    = 'CONTINUE';

COPY INTO RAW_ACCOUNTS  (ACCOUNT_ID,CUSTOMER_ID,ACCOUNT_TYPE,BRANCH_ID,ACCOUNT_STATUS,OPEN_DATE)
    FROM @STG_FIN_BOOTSTRAP/accounts.csv.gz
    FILE_FORMAT = (FORMAT_NAME = FF_CSV_STD)
    ON_ERROR    = 'CONTINUE';

COPY INTO RAW_TRANSACTIONS (TRANSACTION_ID,ACCOUNT_ID,TRANSACTION_TYPE,AMOUNT,CURRENCY,MERCHANT_CATEGORY,TRANSACTION_TIMESTAMP,TRANSACTION_STATUS)
    FROM @STG_FIN_BOOTSTRAP/transactions.csv.gz
    FILE_FORMAT = (FORMAT_NAME = FF_CSV_STD)
    ON_ERROR    = 'CONTINUE';

COPY INTO RAW_LOANS (LOAN_ID,CUSTOMER_ID,LOAN_TYPE,LOAN_AMOUNT,INTEREST_RATE,EMI_AMOUNT,LOAN_STATUS,DISBURSEMENT_DATE)
    FROM @STG_FIN_BOOTSTRAP/loans.csv.gz
    FILE_FORMAT = (FORMAT_NAME = FF_CSV_STD)
    ON_ERROR    = 'CONTINUE';

COPY INTO RAW_BRANCHES (BRANCH_ID,BRANCH_NAME,CITY,STATE,REGION)
    FROM @STG_FIN_BOOTSTRAP/branches.csv.gz
    FILE_FORMAT = (FORMAT_NAME = FF_CSV_STD)
    ON_ERROR    = 'CONTINUE';

COPY INTO RAW_CALENDAR_DIM (DATE_KEY,MONTH,QUARTER,YEAR,FISCAL_PERIOD)
    FROM @STG_FIN_BOOTSTRAP/calendar_dim.csv.gz
    FILE_FORMAT = (FORMAT_NAME = FF_CSV_STD)
    ON_ERROR    = 'CONTINUE';

-- quick row-count audit
SELECT 'RAW_CUSTOMERS'    AS table_name, COUNT(*) AS row_count FROM RAW_CUSTOMERS
UNION ALL SELECT 'RAW_ACCOUNTS',     COUNT(*) FROM RAW_ACCOUNTS
UNION ALL SELECT 'RAW_TRANSACTIONS', COUNT(*) FROM RAW_TRANSACTIONS
UNION ALL SELECT 'RAW_LOANS',        COUNT(*) FROM RAW_LOANS
UNION ALL SELECT 'RAW_BRANCHES',     COUNT(*) FROM RAW_BRANCHES
UNION ALL SELECT 'RAW_CALENDAR_DIM', COUNT(*) FROM RAW_CALENDAR_DIM;
